### ISSUE TITLE
Speedtest library throwing error

### ISSUE THREAD

**Issue by waitblock** [waitblock/notch#1]
### Details

The internet speed test command is broken because of an error being thrown by the speedtest library

### Traceback message
Traceback (most recent call last):
  File "/Users/ethanxu/PycharmProjects/notch/main.py", line 233, in <module>
  File "/Users/ethanxu/PycharmProjects/notch/main.py", line 87, in main
    speed_test_module = speedtest.Speedtest()
  File "/Users/ethanxu/Library/Python/3.8/lib/python/site-packages/speedtest.py", line 1091, in __init__
    self.get_config()
  File "/Users/ethanxu/Library/Python/3.8/lib/python/site-packages/speedtest.py", line 1173, in get_config
    ignore_servers = list(
ValueError: invalid literal for int() with base 10: ''

**Comment by waitblock** [comment]
The internet speed test command will be disabled until this issue is fixed.
